name: Basic CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show files in repo
        run: |
          echo "Listing files..."
          ls -R

      - name: Simulate tests
        run: |
          echo "Running tests..."
          echo "All tests passed ✅"
